spring:
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      security.protocol: PLAINTEXT
    #      socket.connection.setup.timeout.ms: 30000
    admin:
      auto-create-topics: true
    consumer:
      group-id: payments-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "org.example,java.util,java.lang"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://payments-db:5432/payments_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order

server:
  port: 8080
  use-forward-headers: true
  forward-headers-strategy: framework
springdoc:
  api-docs:
    path: /api